linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_final_fields
    - prefer_final_locals

analyzer:
  exclude:
    - test/**
  errors:
    invalid_annotation_target: ignore

